<?php

namespace Abrha\LaravelDataDocs\OpenApi\Concerns;

use Knuckles\Camel\Output\OutputEndpointData;
use Knuckles\Scribe\Tools\Utils;
use Knuckles\Scribe\Writing\OpenApiSpecGenerators\Base31Generator;

/**
 * Merges the custom OpenAPI data produced by the Laravel Data strategies into the
 * field and response schemas generated by the Scribe base generator this trait
 * is applied to.
 */
trait MergesCustomOpenApiData
{
    /**
     * Scribe marks the items of a nullable array field nullable, not the array,
     * so the spec would reject the null Laravel accepts. The field's nullable
     * flag is the property's own, so it moves to the array itself.
     */
    public function generateFieldData($field): array
    {
        $custom = $field['custom']['openAPI'] ?? [];

        if (!($field['nullable'] ?? false) || !Utils::isArrayType((string) ($field['type'] ?? ''))) {
            return $this->merged(parent::generateFieldData($field), $custom);
        }

        if (is_array($field)) {
            $field['nullable'] = false;
        } else {
            $field = clone $field;
            $field->nullable = false;
        }

        $schema = parent::generateFieldData($field);
        $this->applyNullable($schema, true);

        return $this->merged($schema, $custom);
    }

    public function generateSchemaForResponseValue(mixed $value, OutputEndpointData $endpoint, string $path): array
    {
        $schema = parent::generateSchemaForResponseValue($value, $endpoint, $path);

        return $this->merged($schema, $this->responseField($endpoint, $path)?->custom['openAPI'] ?? []);
    }

    /**
     * The item constraints of a custom type on an array field arrive as their
     * own items bag and are merged into the schema's items, which OpenAPI 3.1
     * leaves out of a nullable array response. Every other key stays on the
     * field: an attribute's rule applies to the array itself.
     *
     * @param  array<string, mixed>  $schema
     * @param  array<string, mixed>  $custom
     * @return array<string, mixed>
     */
    private function merged(array $schema, array $custom): array
    {
        $items = $custom['items'] ?? null;
        unset($custom['items']);

        if (is_array($items) && in_array('array', (array) ($schema['type'] ?? null), true)) {
            $schema['items'] = [...(is_array($schema['items'] ?? null) ? $schema['items'] : []), ...$this->customOpenApiData($items)];
        }

        return [...$schema, ...$this->customOpenApiData($custom)];
    }

    /**
     * Scribe walks into an array's items as `items.qty`, while the strategies
     * name a field of an array of Data objects `items[].qty`.
     */
    private function responseField(OutputEndpointData $endpoint, string $path): ?object
    {
        if (isset($endpoint->responseFields[$path])) {
            return $endpoint->responseFields[$path];
        }

        foreach ($endpoint->responseFields as $name => $field) {
            if (str_replace('[]', '', (string) $name) === $path) {
                return $field;
            }
        }

        return null;
    }

    /**
     * @param  array<string, mixed>  $custom
     * @return array<string, mixed>
     */
    private function customOpenApiData(array $custom): array
    {
        return $this instanceof Base31Generator ? $custom : $this->withBooleanExclusiveBounds($custom);
    }

    /**
     * The pipeline writes exclusive bounds as numbers, as OpenAPI 3.1 takes them.
     * OpenAPI 3.0 takes a boolean that makes minimum or maximum exclusive, so the
     * bound moves there; of an inclusive and an exclusive bound on one side, the
     * stricter is kept.
     *
     * @param  array<string, mixed>  $custom
     * @return array<string, mixed>
     */
    private function withBooleanExclusiveBounds(array $custom): array
    {
        foreach (['minimum' => 'exclusiveMinimum', 'maximum' => 'exclusiveMaximum'] as $inclusive => $exclusive) {
            if (!is_int($custom[$exclusive] ?? null) && !is_float($custom[$exclusive] ?? null)) {
                continue;
            }

            $bound = $custom[$exclusive];
            $stricter = !isset($custom[$inclusive])
                || ($inclusive === 'minimum' ? $bound >= $custom[$inclusive] : $bound <= $custom[$inclusive]);

            if ($stricter) {
                $custom[$inclusive] = $bound;
                $custom[$exclusive] = true;
            } else {
                unset($custom[$exclusive]);
            }
        }

        return $custom;
    }
}
