<?php

namespace Abrha\LaravelDataDocs\OpenApi;

use Abrha\LaravelDataDocs\OpenApi\Concerns\MergesCustomOpenApiData;
use Knuckles\Camel\Output\OutputEndpointData;
use Knuckles\Scribe\Tools\DocumentationConfig;
use Knuckles\Scribe\Writing\OpenAPISpecWriter;
use Knuckles\Scribe\Writing\OpenApiSpecGenerators\Base31Generator;
use Knuckles\Scribe\Writing\OpenApiSpecGenerators\BaseGenerator;
use Knuckles\Scribe\Writing\OpenApiSpecGenerators\OpenApiGenerator;

/**
 * Extended OpenAPI generator that merges custom OpenAPI data generated by Laravel Data strategies.
 *
 * This generator works in conjunction with the Laravel Data documentation generation services
 * to include additional OpenAPI schema information (like default values, custom properties, etc.)
 * that are extracted from Laravel Data DTOs and their attributes.
 *
 * Path items are rebuilt by the Scribe base generator matching the configured `openapi.version`,
 * so OpenAPI 3.1 output keeps its 3.1 schema shape. The document root is left untouched, so the
 * `openapi.overrides` applied by earlier generators survive.
 */
final class ExtendedOpenApiGenerator extends OpenApiGenerator
{
    private BaseGenerator $generator;

    public function __construct(DocumentationConfig $config)
    {
        parent::__construct($config);

        $version = $config->get('openapi.version', OpenAPISpecWriter::SPEC_VERSION);

        if (version_compare($version, '3.1.0', '>=')) {
            $this->generator = new class ($config) extends Base31Generator {
                use MergesCustomOpenApiData;
            };

            return;
        }

        $this->generator = new class ($config) extends BaseGenerator {
            use MergesCustomOpenApiData;
        };
    }

    public function pathItem(array $pathItem, array $groupedEndpoints, OutputEndpointData $endpoint): array
    {
        return $this->generator->pathItem($pathItem, $groupedEndpoints, $endpoint);
    }

    public function pathParameters(array $parameters, array $endpoints, array $urlParameters): array
    {
        return $this->generator->pathParameters($parameters, $endpoints, $urlParameters);
    }

    public function generateFieldData($field): array
    {
        return $this->generator->generateFieldData($field);
    }

    public function generateSchemaForResponseValue(mixed $value, OutputEndpointData $endpoint, string $path): array
    {
        return $this->generator->generateSchemaForResponseValue($value, $endpoint, $path);
    }
}
