<?php

namespace Abrha\LaravelDataDocs\OpenApi;

use Knuckles\Scribe\Writing\OpenApiSpecGenerators\BaseGenerator;

/**
 * Extended OpenAPI generator that merges custom OpenAPI data generated by Laravel Data strategies.
 *
 * This generator works in conjunction with the Laravel Data documentation generation services
 * to include additional OpenAPI schema information (like default values, custom properties, etc.)
 * that are extracted from Laravel Data DTOs and their attributes.
 */
class ExtendedOpenApiGenerator extends BaseGenerator
{
    public function generateFieldData($field): array
    {
        $generateFieldData = parent::generateFieldData($field);

        // Merge in custom OpenAPI data generated by Laravel Data strategies
        return [...$generateFieldData, ...$field['custom']['openAPI'] ?? []];
    }
}
